name: Recommend - AU

on:
  schedule:
    - cron: '30 0 * * 1-5'   # KST 09:30
    - cron: '30 4 * * 1-5'   # KST 13:30
  workflow_dispatch:

jobs:
  run-au:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install setuptools
          pip install -r requirements.txt

      - name: Run AU Action
        env:
          MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: python scripts/action_runner.py --country au
